"""Core data models for Shesha."""

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from shesha.project import Project


@dataclass
class ProjectInfo:
    """Metadata about a project's source."""

    project_id: str
    source_url: str | None
    is_local: bool
    source_exists: bool
    analysis_status: Literal["current", "stale", "missing"] | None = None


@dataclass
class ParsedDocument:
    """A parsed document ready for storage and querying."""

    name: str
    content: str
    format: str
    metadata: dict[str, str | int | float | bool]
    char_count: int
    parse_warnings: list[str] = field(default_factory=list)


@dataclass
class RepoProjectResult:
    """Result from create_project_from_repo()."""

    project: "Project"
    status: Literal["created", "unchanged", "updates_available"]
    files_ingested: int
    files_skipped: int = 0
    warnings: list[str] = field(default_factory=list)
    _apply_updates_fn: Callable[[], "RepoProjectResult"] | None = field(default=None, repr=False)

    def apply_updates(self) -> "RepoProjectResult":
        """Pull changes and re-ingest. Only valid when status is 'updates_available'."""
        if self.status != "updates_available":
            raise ValueError("apply_updates() is only valid when status is 'updates_available'")
        if self._apply_updates_fn is None:
            raise ValueError("No apply_updates function provided")
        return self._apply_updates_fn()


@dataclass
class QueryContext:
    """Metadata about a query for trace logging."""

    trace_id: str
    question: str
    document_ids: list[str]
    model: str
    system_prompt: str
    subcall_prompt: str


@dataclass
class AnalysisComponent:
    """A component within a codebase analysis."""

    name: str
    path: str
    description: str
    apis: list[dict[str, Any]]
    models: list[str]
    entry_points: list[str]
    internal_dependencies: list[str]
    auth: str | None = None
    data_persistence: str | None = None


@dataclass
class AnalysisExternalDep:
    """An external dependency in a codebase analysis."""

    name: str
    type: str  # external_api, database, message_queue, ai_service, auth_service, storage
    description: str
    used_by: list[str]
    optional: bool = False


@dataclass
class RepoAnalysis:
    """Pre-computed codebase analysis for HLD builder optimization."""

    version: str
    generated_at: str
    head_sha: str
    overview: str
    components: list[AnalysisComponent]
    external_dependencies: list[AnalysisExternalDep]
    caveats: str = "This analysis was generated by AI and may be incomplete or incorrect."
